name: "Build e release"
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-slim
        steps:
            - name: "Checkout the project"
              uses: actions/checkout@v5

            - name: "Setup node"
              uses: actions/setup-node@v6
              with:
                  node-version: ">=22"

            - name: "Install dependencies"
              run: npm install --force

            - name: Set up new version
              run: npx semantic-release
              working-directory: ./projects/ds

            - name: "Build library"
              run: npx ng build ds

    deployment:
        runs-on: ubuntu-slim
        needs: [build]
        steps:
            - name: "Starting deployment"
              run: echo "Deploy started"
